# Generated by Django 4.0.5 on 2022-06-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehiculo_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=80, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('fnacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=1, verbose_name='sexo')),
                ('telefono', models.CharField(max_length=14, verbose_name='Teléfono')),
                ('fingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fsalida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('fresponsable', models.CharField(max_length=80, verbose_name='Famliar responsable')),
                ('tcontacto', models.CharField(max_length=14, verbose_name='Teléfono contacto')),
                ('correo', models.CharField(max_length=70, verbose_name='Correo')),
                ('antmedicos', models.CharField(blank=True, max_length=800, null=True, verbose_name='Antecedentes Médicos')),
                ('alergias', models.CharField(blank=True, max_length=800, null=True, verbose_name='Alergias')),
                ('enfermedades', models.CharField(blank=True, max_length=800, null=True, verbose_name='Enfermedades Pre-existentes')),
                ('medicamentos', models.CharField(blank=True, max_length=800, null=True, verbose_name='medicamentos uso diario')),
                ('habitacion', models.CharField(max_length=3, verbose_name='Nro. de Habitación')),
                ('cuidados', models.CharField(max_length=30, verbose_name='Nivel de cuidado')),
                ('foto', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='foto')),
            ],
        ),
    ]
